### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by VinodKumar9576** [trsvchn/colab-badge-action#11]
Hi,

Finally i found a solution to what i'm looking for after many days.
But couldn't quite understand how this works.
Can you please make a small tutorial or steps how to install and use the 'colab-badge-action'.
Appreciate your help.
Thank you.

**Comment by VinodKumar9576** [comment]
@skearnes  can you look iinto this.

**Comment by skearnes** [comment]
Hi, it's often helpful to search and see how other people have used code you're looking into. For instance, there are more than 50 examples on GitHub: https://github.com/search?q=colab-badge-action&type=Code

**Comment by VinodKumar9576** [comment]
Hi I've gone through the other's examples.
But none of them show whether to import any package or how they are getting the badge.
There are just their outputs in it.

I would appreciate very much if you provide the steps like any package needs to be imported in python notebook to make the badge or how to make it.

**Comment by skearnes** [comment]
That process is explained here: https://github.com/trsvchn/colab-badge-action#badge-tag

**Comment by VinodKumar9576** [comment]
do i have to import it in jupyter notebook and that it works?

**Comment by tarasio-mirror** [comment]
Hi, @VinodKumar9576 !
Thank you for your interest!

This tool specially designed for [GitHub Actions](https://github.com/features/actions) to automate colab badge routines. It is configured and launches automatically on GitHub's VM.

Do you want (prefer) to use it locally instead?

**Comment by VinodKumar9576** [comment]
Hi @trsvchn 
Thanks for answering and for your time.
Actually i work on colab and i push all my work to Github through command line which doesn't make "colab badge" while pushing. (when i save notebooks via 'save a copy in github option' i have a chance to include badge).
So i was looking online whether i can make a badge via code in colab notebook itself and stumbled upon your tool.

I'm just confused how to use this tool and get it worked to get colab badge.

I've gone through the link you shared and saw that giving {{badge}} tag makes badge in notebook but prior to that do i have to import or install anything in colab.

Hope my requirement is clear to you.

Appreciate your support.

**Comment by tarasio-mirror** [comment]
Welcome back!
And sorry for a late response. There was a some work to do, since I want to keep this action to be simple, modular and handy at once.

Anyway, I released a new version `v2` of the action. It is going to be simpler and easier to use w/o advanced GH actions scripting.

**How it works?**

1. You work in jupyter as usual, no matter where, in Colab, or in local. You just need to add `{{ badge }}` inside markdown cell to point where the badge will be placed.
2. Then commit changes and push to GitHub.
3. Here goes `colab-badge-action`. It looks inside notebooks for `{{ badge }}` tag and replace it w/ a badge. After that it commits changes and pushes back to repo/branch.

Thus, you do not need import anything in your environment. You just need to setup your GitHub action workflow and "activate" `colab-badge-action`. To do that:
1. inside your repo on github create folder `.github`, inside that folder create another `workflows` folder w/ yaml file `main.yml`.
2. Configure action in `main.yml` file, here is working example:

```yaml
# .github/workflows/main.yml
name: Test Colab Badge Action
on: [push]

jobs:
  build:
    name: Colab Badge Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@master
      - name: Add/Update badges
        id: badges
        uses: trsvchn/colab-badge-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check: 'all'
          update: true
          target_branch: master
          target_repository: trsvchn/colab-badge-action-v2-test
```
Note: don't forget to use `checkout` action first: `actions/checkout@master`
Note: use `v2` of the action: `trsvchn/colab-badge-action@v2`
Here is full test example: 
https://github.com/trsvchn/colab-badge-action-v2-test

See README for more action's inputs descriptions and do not hesitate to ask for help here!

And thank you for your patience! Have fun!)
