### ISSUE TITLE
Remove commiting and pushing from the action, leave only basic core feature: creating badge

### ISSUE THREAD

**Issue by tarasio-mirror** [trsvchn/colab-badge-action#14]
What we want to achieve is this

```yaml
jobs:
  build:
    steps:
      - name: Checkout Action
        uses: actions/checkout@v2

      - name: Colab Badge Action
        # Add/update colab badges (modify files)
        uses: trsvchn/colab-badge-action@new_version
        with:
          ...
     
      - name: Commit and Push Changed Notebooks
        # Use your favorite action here
        uses: action@commit
        with:
          ...
```
