### ISSUE TITLE
Bug: Badges do not update in markdown files.

### ISSUE THREAD

**Issue by startakovsky** [trsvchn/colab-badge-action#17]
### Summary: 
 > Colab badges in Jupyter Notebooks update across branches when merging or pushing, but Colab badges in Markdown files do not update. They will be created just fine, but not updated once created.

### Steps to Reproduce
 1. Make a new repo, clone it
 2. Checkout a new branch `git checkout -b test`
 3. Create a Jupyter notebook file named `test` at the root of the repository
 4. Make a markdown cell with `{{ badge }}`.
 5. Create a markdown file: `echo '
 6. Write first line `{{ badge test }}`
 7. Commit: `git commit -am "test"`
 8. Push: `git push -u origin test`
 9. Watch the action complete, hopefully successfully. Confirm that the branch `test`
    - created a new badge in _test.ipynb_
    - created a new badge in _test.md_
    - Note that the paths in both badges respect the current test branch.
 10. Create a pull request with the `test` branch to the `main` branch.
 11. Watch the github action do the following:
    - update the badge in _test.ipynb_
    - Skip updating the badge in _test.md_ **<<-- This is the bug.**

Note: You can inspect the action since the yaml below creates verbose output and see that 

Goes in .github/workflows/colab_badge.yml
```yaml
name: Badges workflow
on: [push]

jobs:
  build:
    name: Badges Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout first
        id: checkout
        uses: actions/checkout@v2

      - name: Add/Update badges
        id: badges
        uses: trsvchn/colab-badge-action@v4
        with:
          check: 'all'
          update: true
          verbose: true

      - name: push
        uses: actions-x/commit@v6
        with:
          message: Update Colab badges with GitHub Actions
```
