### ISSUE TITLE
Possible Bug: Branch name changing from branch to `master` and I'm wondering why.

### ISSUE THREAD

**Issue by startakovsky** [trsvchn/colab-badge-action#18]
Hello!

It seems that with the default settings, pasted below I am getting an error where the branch name keeps getting switched to master even though I am using the default settings.  See image (see below). 

Thank you for your help!
Steven

<img width="241" alt="image" src="https://user-images.githubusercontent.com/689723/168190592-8ea1cd96-262b-4e47-a603-b1c52a3a9e0d.png">

```yaml
name: Badges workflow
on: [workflow_dispatch, push]
jobs:
  build:
    name: Badges Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout first
        id: checkout
        uses: actions/checkout@v2

      - name: Add/Update badges
        id: badges
        uses: trsvchn/colab-badge-action@v4
        with:
          check: 'all'
          update: true
          verbose: true

      - name: push
        uses: actions-x/commit@v6
        with:
          message: Update Colab badges with GitHub Actions
```
